FROM python:3.7

ENV STREAMLIT_FILE="streamlit_app.py"
ENV STREAMLIT_PORT=5005
ENV STREAMLIT_IP=0.0.0.0
ENV COMET_API_KEY=${COMET_API_KEY}

WORKDIR /code

ADD ift6758/requirements_st.txt ./

RUN pip3 install -r requirements_st.txt

ADD ift6758 ./ift6758/
ADD streamlit_app.py .

ENTRYPOINT [ "streamlit", "run", "streamlit_app.py" ]
EXPOSE ${STREAMLIT_PORT}

CMD [ "--server.port=5005", "--server.address=0.0.0.0" ]
